### ISSUE TITLE
not a library

### ISSUE THREAD

**Issue by r-cohen** [gabriel-TheCode/OnboardingViewPagerExamples#4]
well, would have been a really cool library if it was a real library instead of just an example. why don't you make it one, and publish it on a maven repository like Jitpack for example? just a thought.

**Comment by gabriel-TheCode** [comment]
I thought about it at the beginning, but I finally decide to make it an open source project that would allow people to reappropriate it as they please, also, I didn't want to ask myself too many questions about the best possible implementation of this as a lib. Just wanted to code something cool and share it.
