### ISSUE TITLE
disable page indicator dots

### ISSUE THREAD

**Issue by r-cohen** [gabriel-TheCode/OnboardingViewPagerExamples#5]
a `TabLayout` is used for displaying the dots. clicking on the dots doesn't look that great. also, it should be preferable to disable it for multiple reasons. we might not want the user to skip pages.

**Comment by gabriel-TheCode** [comment]
You can update the code as you want to fit your need. It’s not a library, just a showcase project to demonstrate how to create onboarding view pagers.
